import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'label-caps': ['Inter', ...defaultTheme.fontFamily.sans],
                'stat-display': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-xl-mobile': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-xl': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-sm': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-lg-mobile': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'label-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body-sm': ['Inter', ...defaultTheme.fontFamily.sans],
                'label-md': ['Inter', ...defaultTheme.fontFamily.sans],
                'body-md': ['Inter', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
                'stat-display': ['32px', { lineHeight: '38px', fontWeight: '700' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
                'headline-xl-mobile': ['26px', { lineHeight: '34px', fontWeight: '700' }],
                'headline-xl': ['36px', { lineHeight: '44px', fontWeight: '700' }],
                'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
                'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '600' }],
                'label-lg': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
                'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
                'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
            },
            colors: {
                'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
                'on-tertiary-fixed-variant': 'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)',
                'on-error': 'rgb(var(--color-on-error) / <alpha-value>)',
                'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
                'on-secondary-fixed': 'rgb(var(--color-on-secondary-fixed) / <alpha-value>)',
                'primary-fixed-dim': 'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
                'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
                'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
                'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value>)',
                'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
                tertiary: 'rgb(var(--color-tertiary) / <alpha-value>)',
                'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
                'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
                'secondary-fixed-dim': 'rgb(var(--color-secondary-fixed-dim) / <alpha-value>)',
                'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
                'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
                'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value>)',
                surface: 'rgb(var(--color-surface) / <alpha-value>)',
                'tertiary-fixed-dim': 'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
                'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
                primary: 'rgb(var(--color-primary) / <alpha-value>)',
                'tertiary-fixed': 'rgb(var(--color-tertiary-fixed) / <alpha-value>)',
                'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
                error: 'rgb(var(--color-error) / <alpha-value>)',
                'surface-tint': 'rgb(var(--color-surface-tint) / <alpha-value>)',
                'on-tertiary': 'rgb(var(--color-on-tertiary) / <alpha-value>)',
                'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
                'on-primary-fixed-variant': 'rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)',
                'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
                'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
                'on-tertiary-fixed': 'rgb(var(--color-on-tertiary-fixed) / <alpha-value>)',
                'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
                secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
                'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value>)',
                'secondary-fixed': 'rgb(var(--color-secondary-fixed) / <alpha-value>)',
                'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value>)',
                'primary-fixed': 'rgb(var(--color-primary-fixed) / <alpha-value>)',
                'on-tertiary-container': 'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
                'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
                outline: 'rgb(var(--color-outline) / <alpha-value>)',
                'on-secondary-fixed-variant': 'rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)',
                'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
                'on-background': 'rgb(var(--color-on-background) / <alpha-value>)',
                'on-primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
                'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
                'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
                background: 'rgb(var(--color-background) / <alpha-value>)',

                // Tokens de marca (morado/dorado) usados en el resto de la app, con equivalentes para modo oscuro
                'brand-page-from': 'rgb(var(--color-brand-page-from) / <alpha-value>)',
                'brand-page-to': 'rgb(var(--color-brand-page-to) / <alpha-value>)',
                'brand-card': 'rgb(var(--color-brand-card) / <alpha-value>)',
                'brand-card-alt': 'rgb(var(--color-brand-card-alt) / <alpha-value>)',
                'brand-ink': 'rgb(var(--color-brand-ink) / <alpha-value>)',
                'brand-muted': 'rgb(var(--color-brand-muted) / <alpha-value>)',
                'brand-border': 'rgb(var(--color-brand-border) / <alpha-value>)',
            },
        },
    },

    plugins: [forms],
};
